name: Build And Publish Snapshot
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and publish snapshot
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew --warning-mode all build -x test

      - name: Test
        run: ./gradlew --no-daemon --max-workers=2 --warning-mode=all test --continue
        if: "!contains(github.event.head_commit.message, '[i am bad and i hate unit tests]')"

      - name: Publish snapshot
        run: ./gradlew -x test -PsonatypeUsername=${{ secrets.FLOW_JVM_SDK_SONATYPE_USERNAME }} -PsonatypePassword=${{ secrets.FLOW_JVM_SDK_SONATYPE_PASSWORD }} -PgroupId=${{ secrets.FLOW_JVM_SDK_SONATYPE_GROUP_ID }} -PsnapshotDate=${{ steps.date.outputs.date }} publishToSonatype closeAndReleaseSonatypeStagingRepository
